# Generated by Django 4.2.9 on 2024-05-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Classroom_API_Settings",
            new_name="Settings",
        ),
    ]
