# Generated by Django 4.2.9 on 2024-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="google_credentials",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="last_check",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="token_pickle_base64",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="webhook_url",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="webhook_url_test",
            field=models.TextField(default="", null=True),
        ),
    ]
