# Generated by Django 4.2.9 on 2024-05-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_settings_google_credentials_settings_last_check_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
