# Generated by Django 4.2.9 on 2024-05-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_classroom_api_settings_settings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
