# Generated by Django 4.2.9 on 2024-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="google_credentials",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="token_pickle_base64",
        ),
        migrations.AddField(
            model_name="settings",
            name="google_creds",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="utils_server_password",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="utils_server_url",
            field=models.TextField(default="", null=True),
        ),
    ]
